export const THEMES = {
  light: {
    id: 'light',
    name: 'Light',
    nameFA: 'روشن',
    sidebar: {
      bg: '#ffffff',
      border: '#f0f0f0',
      logoBg: '#0f112e',
      logoColor: '#ffffff',
      navActive: '#0f112e',
      navActiveTxt: '#ffffff',
      navHover: '#f5f5f5',
      navTxt: '#6b7280',
      groupLabel: '#767676',
    },
    topbar: {
      bg: '#ffffff',
      border: '#f0f0f0',
      txt: '#111111',
      searchBg: '#f5f5f5',
      searchTxt: '#707070',
      iconColor: '#6b7280',
    },
    content: {
      bg: '#f9fafb',
      cardBg: '#ffffff',
      cardBorder: '#f0f0f0',
      txt: '#111111',
      txtMuted: '#767676',
      barMain: '#0f112e',
      barSub: '#e5e7eb',
      accent: '#0f112e',
      accentLight: '#eef0f7',
    },
  },

  dark: {
    id: 'dark',
    name: 'Dark',
    nameFA: 'تاریک',
    sidebar: {
      bg: '#1a1a2e',
      border: '#2a2a3e',
      logoBg: '#6366f1',
      logoColor: '#ffffff',
      navActive: '#6366f1',
      navActiveTxt: '#ffffff',
      navHover: '#252540',
      navTxt: '#9ca3b8',
      groupLabel: '#848484',
    },
    topbar: {
      bg: '#1a1a2e',
      border: '#2a2a3e',
      txt: '#f1f5f9',
      searchBg: '#252540',
      searchTxt: '#8e8e8e',
      iconColor: '#6b7280',
    },
    content: {
      bg: '#13131f',
      cardBg: '#1a1a2e',
      cardBorder: '#2a2a3e',
      txt: '#f1f5f9',
      txtMuted: '#848484',
      barMain: '#6366f1',
      barSub: '#2a2a3e',
      accent: '#6366f1',
      accentLight: '#1e1f3a',
    },
  },

  navy: {
    id: 'navy',
    name: 'Navy',
    nameFA: 'نیروی دریایی',
    sidebar: {
      bg: '#0f172a',
      border: '#1e293b',
      logoBg: '#38bdf8',
      logoColor: '#0f172a',
      navActive: '#1e3a5f',
      navActiveTxt: '#38bdf8',
      navHover: '#1e293b',
      navTxt: '#64748b',
      groupLabel: '#808080',
    },
    topbar: {
      bg: '#0f172a',
      border: '#1e293b',
      txt: '#e2e8f0',
      searchBg: '#1e293b',
      searchTxt: '#8f8f8f',
      iconColor: '#475569',
    },
    content: {
      bg: '#080f1e',
      cardBg: '#0f172a',
      cardBorder: '#1e293b',
      txt: '#e2e8f0',
      txtMuted: '#808080',
      barMain: '#38bdf8',
      barSub: '#1e293b',
      accent: '#38bdf8',
      accentLight: '#0c2340',
    },
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald',
    nameFA: 'زمرد',
    sidebar: {
      bg: '#ffffff',
      border: '#d1fae5',
      logoBg: '#059669',
      logoColor: '#ffffff',
      navActive: '#059669',
      navActiveTxt: '#ffffff',
      navHover: '#f0faf5',
      navTxt: '#6b7280',
      groupLabel: '#767676',
    },
    topbar: {
      bg: '#ffffff',
      border: '#d1fae5',
      txt: '#111111',
      searchBg: '#f0faf5',
      searchTxt: '#707070',
      iconColor: '#6b7280',
    },
    content: {
      bg: '#f0faf5',
      cardBg: '#ffffff',
      cardBorder: '#d1fae5',
      txt: '#111111',
      txtMuted: '#767676',
      barMain: '#059669',
      barSub: '#d1fae5',
      accent: '#059669',
      accentLight: '#ecfdf5',
    },
  },

  violet: {
    id: 'violet',
    name: 'Violet',
    nameFA: 'بنفش',
    sidebar: {
      bg: '#faf5ff',
      border: '#ede9fe',
      logoBg: '#7c3aed',
      logoColor: '#ffffff',
      navActive: '#7c3aed',
      navActiveTxt: '#ffffff',
      navHover: '#f5f3ff',
      navTxt: '#7c3aed',
      groupLabel: '#717171',
    },
    topbar: {
      bg: '#ffffff',
      border: '#ede9fe',
      txt: '#1e1b4b',
      searchBg: '#f5f3ff',
      searchTxt: '#707070',
      iconColor: '#7c3aed',
    },
    content: {
      bg: '#f5f3ff',
      cardBg: '#ffffff',
      cardBorder: '#ede9fe',
      txt: '#1e1b4b',
      txtMuted: '#7c3aed',
      barMain: '#7c3aed',
      barSub: '#ddd6fe',
      accent: '#7c3aed',
      accentLight: '#ede9fe',
    },
  },
}

export const DEFAULT_THEME = 'light'
export const THEME_STORAGE_KEY = 'hesabyar_theme'
