export const THEMES = {
  light: {
    id: 'light',
    name: 'Light',
    label: 'روشن',
    icon: '☀️',
    vars: {
      '--theme-sidebar-bg':         '#ffffff',
      '--theme-sidebar-border':     '#f0f0f0',
      '--theme-sidebar-logo-bg':    '#0f112e',
      '--theme-sidebar-logo-color': '#ffffff',
      '--theme-nav-active-bg':      '#0f112e',
      '--theme-nav-active-txt':     '#ffffff',
      '--theme-nav-hover-bg':       '#f5f5f5',
      '--theme-nav-txt':            '#6b7280',
      '--theme-nav-group-txt':      '#9ca3af',
      '--theme-topbar-bg':          '#ffffff',
      '--theme-topbar-border':      '#f0f0f0',
      '--theme-topbar-txt':         '#111111',
      '--theme-search-bg':          '#f5f5f5',
      '--theme-search-txt':         '#9ca3af',
      '--theme-content-bg':         '#f9fafb',
      '--theme-card-bg':            '#ffffff',
      '--theme-card-border':        '#f0f0f0',
      '--theme-card-txt':           '#111111',
      '--theme-card-muted':         '#9ca3af',
      '--theme-accent':             '#0f112e',
      '--theme-accent-light':       '#e8eaf6',
      '--theme-accent-txt':         '#0f112e',
      '--theme-bar-main':           '#0f112e',
      '--theme-bar-sub':            '#e5e7eb',
      '--theme-badge-bg':           '#e8eaf6',
      '--theme-badge-txt':          '#0f112e',
      '--theme-user-avatar-bg':     '#e8eaf6',
      '--theme-user-avatar-txt':    '#3949ab',
      '--theme-scrollbar':          '#e5e7eb',
    },
  },

  dark: {
    id: 'dark',
    name: 'Dark',
    label: 'تاریک',
    icon: '🌙',
    vars: {
      '--theme-sidebar-bg':         '#1a1a2e',
      '--theme-sidebar-border':     '#2a2a3e',
      '--theme-sidebar-logo-bg':    '#6366f1',
      '--theme-sidebar-logo-color': '#ffffff',
      '--theme-nav-active-bg':      '#6366f1',
      '--theme-nav-active-txt':     '#ffffff',
      '--theme-nav-hover-bg':       '#252540',
      '--theme-nav-txt':            '#9ca3b8',
      '--theme-nav-group-txt':      '#4b5563',
      '--theme-topbar-bg':          '#1a1a2e',
      '--theme-topbar-border':      '#2a2a3e',
      '--theme-topbar-txt':         '#f1f5f9',
      '--theme-search-bg':          '#252540',
      '--theme-search-txt':         '#6b7280',
      '--theme-content-bg':         '#13131f',
      '--theme-card-bg':            '#1a1a2e',
      '--theme-card-border':        '#2a2a3e',
      '--theme-card-txt':           '#f1f5f9',
      '--theme-card-muted':         '#6b7280',
      '--theme-accent':             '#6366f1',
      '--theme-accent-light':       '#2a2a3e',
      '--theme-accent-txt':         '#6366f1',
      '--theme-bar-main':           '#6366f1',
      '--theme-bar-sub':            '#2a2a3e',
      '--theme-badge-bg':           '#252540',
      '--theme-badge-txt':          '#a5b4fc',
      '--theme-user-avatar-bg':     '#252540',
      '--theme-user-avatar-txt':    '#a5b4fc',
      '--theme-scrollbar':          '#2a2a3e',
    },
  },

  navy: {
    id: 'navy',
    name: 'Navy',
    label: 'نیروی دریایی',
    icon: '🌊',
    vars: {
      '--theme-sidebar-bg':         '#0f172a',
      '--theme-sidebar-border':     '#1e293b',
      '--theme-sidebar-logo-bg':    '#38bdf8',
      '--theme-sidebar-logo-color': '#0f172a',
      '--theme-nav-active-bg':      '#1e3a5f',
      '--theme-nav-active-txt':     '#38bdf8',
      '--theme-nav-hover-bg':       '#1e293b',
      '--theme-nav-txt':            '#64748b',
      '--theme-nav-group-txt':      '#334155',
      '--theme-topbar-bg':          '#0f172a',
      '--theme-topbar-border':      '#1e293b',
      '--theme-topbar-txt':         '#e2e8f0',
      '--theme-search-bg':          '#1e293b',
      '--theme-search-txt':         '#475569',
      '--theme-content-bg':         '#080f1e',
      '--theme-card-bg':            '#0f172a',
      '--theme-card-border':        '#1e293b',
      '--theme-card-txt':           '#e2e8f0',
      '--theme-card-muted':         '#475569',
      '--theme-accent':             '#38bdf8',
      '--theme-accent-light':       '#1e293b',
      '--theme-accent-txt':         '#38bdf8',
      '--theme-bar-main':           '#38bdf8',
      '--theme-bar-sub':            '#1e293b',
      '--theme-badge-bg':           '#1e3a5f',
      '--theme-badge-txt':          '#38bdf8',
      '--theme-user-avatar-bg':     '#1e3a5f',
      '--theme-user-avatar-txt':    '#38bdf8',
      '--theme-scrollbar':          '#1e293b',
    },
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald',
    label: 'زمرد',
    icon: '💚',
    vars: {
      '--theme-sidebar-bg':         '#ffffff',
      '--theme-sidebar-border':     '#d1fae5',
      '--theme-sidebar-logo-bg':    '#059669',
      '--theme-sidebar-logo-color': '#ffffff',
      '--theme-nav-active-bg':      '#059669',
      '--theme-nav-active-txt':     '#ffffff',
      '--theme-nav-hover-bg':       '#f0faf5',
      '--theme-nav-txt':            '#6b7280',
      '--theme-nav-group-txt':      '#9ca3af',
      '--theme-topbar-bg':          '#ffffff',
      '--theme-topbar-border':      '#d1fae5',
      '--theme-topbar-txt':         '#111111',
      '--theme-search-bg':          '#f0faf5',
      '--theme-search-txt':         '#9ca3af',
      '--theme-content-bg':         '#f0faf5',
      '--theme-card-bg':            '#ffffff',
      '--theme-card-border':        '#d1fae5',
      '--theme-card-txt':           '#111111',
      '--theme-card-muted':         '#6b7280',
      '--theme-accent':             '#059669',
      '--theme-accent-light':       '#d1fae5',
      '--theme-accent-txt':         '#059669',
      '--theme-bar-main':           '#059669',
      '--theme-bar-sub':            '#d1fae5',
      '--theme-badge-bg':           '#d1fae5',
      '--theme-badge-txt':          '#065f46',
      '--theme-user-avatar-bg':     '#d1fae5',
      '--theme-user-avatar-txt':    '#065f46',
      '--theme-scrollbar':          '#d1fae5',
    },
  },

  violet: {
    id: 'violet',
    name: 'Violet',
    label: 'بنفش',
    icon: '💜',
    vars: {
      '--theme-sidebar-bg':         '#faf5ff',
      '--theme-sidebar-border':     '#ede9fe',
      '--theme-sidebar-logo-bg':    '#7c3aed',
      '--theme-sidebar-logo-color': '#ffffff',
      '--theme-nav-active-bg':      '#7c3aed',
      '--theme-nav-active-txt':     '#ffffff',
      '--theme-nav-hover-bg':       '#f5f3ff',
      '--theme-nav-txt':            '#7c3aed',
      '--theme-nav-group-txt':      '#a78bfa',
      '--theme-topbar-bg':          '#ffffff',
      '--theme-topbar-border':      '#ede9fe',
      '--theme-topbar-txt':         '#1e1b4b',
      '--theme-search-bg':          '#f5f3ff',
      '--theme-search-txt':         '#a78bfa',
      '--theme-content-bg':         '#f5f3ff',
      '--theme-card-bg':            '#ffffff',
      '--theme-card-border':        '#ede9fe',
      '--theme-card-txt':           '#1e1b4b',
      '--theme-card-muted':         '#7c3aed',
      '--theme-accent':             '#7c3aed',
      '--theme-accent-light':       '#ede9fe',
      '--theme-accent-txt':         '#7c3aed',
      '--theme-bar-main':           '#7c3aed',
      '--theme-bar-sub':            '#ddd6fe',
      '--theme-badge-bg':           '#ede9fe',
      '--theme-badge-txt':          '#4c1d95',
      '--theme-user-avatar-bg':     '#ede9fe',
      '--theme-user-avatar-txt':    '#6d28d9',
      '--theme-scrollbar':          '#ddd6fe',
    },
  },
}

export const THEME_IDS = Object.keys(THEMES)
export const DEFAULT_THEME = 'light'
